//blog posts
export const GET_BLOGPOST_START = "GET_BLOGPOST_START";
export const GET_BLOGPOST_SUCCESS = "GET_BLOGPOST_SUCCESS";
export const GET_BLOGPOST_ERROR = "GET_BLOGPOST_ERROR";

//blog post single
export const GET_SINGLE_POST_START = "GET_SINGLE_POST_START";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
export const GET_SINGLE_POST_ERROR = "GET_SINGLE_POST_ERROR";

//github projects
export const GET_PROJECT_START = "GET_PROJECT_START";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_ERROR = "GET_PROJECT_ERROR";
